# This defines a workflow to replay transactions on the given chain with the latest aptos node software.
# In order to trigger it go to the Actions Tab of the Repo, click "replay-verify" and then "Run Workflow".
#
# On PR, a single test case will run. On workflow_dispatch, you may specify the CHAIN_NAME to verify.

name: "provision-replay-verify-archive-disks"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      NETWORK:
        required: true
        type: string
        description: The network to provision storage for.
      BRANCH:
        type: string
        description: The branch to provision storage for.
  pull_request:
    paths:
      - '.github/workflows/provision-replay-verify-archive-disks.yaml'
      - '.github/workflows/workflow-run-replay-verify-archive-storage-provision.yaml'
  schedule:
    - cron: "0 22 * * 0,2,4" # The main branch cadence. This runs every Sun,Tues,Thurs

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation which we use to login into Google Artifact Registry
  issues: read
  pull-requests: read

jobs:
  replay-testnet:
    uses: ./.github/workflows/workflow-run-replay-verify-archive-storage-provision.yaml
    secrets: inherit
    with:
      NETWORK: testnet
      BRANCH: ${{ github.event.inputs.BRANCH }}
  replay-mainnet:
    uses: ./.github/workflows/workflow-run-replay-verify-archive-storage-provision.yaml
    secrets: inherit
    with:
      NETWORK: mainnet
      BRANCH: ${{ github.event.inputs.BRANCH }}